---
version: '3.6'




x-quorum-def:
  &quorum-def
  restart: "on-failure"
  build:
    context: config/goquorum
    args:
      QUORUM_VERSION: ${QUORUM_VERSION:-latest}
  expose:
    - 30303
    - 8545
    - 9545
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s






  




services:

  validator1:
    << : *quorum-def
    ports:
      - 21001:8545/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
    volumes:
      - ./config/nodes/validator1:/config/keys
      - ./logs/quorum:/var/log/quorum/
      - ./config/permissions:/permissions
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.11

  validator2:
    << : *quorum-def
    ports:
      - 21002:8545/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
    volumes:
      - ./config/nodes/validator2:/config/keys
      - ./logs/quorum:/var/log/quorum/
      - ./config/permissions:/permissions
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.12

  validator3:
    << : *quorum-def
    ports:
      - 21003:8545/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
    volumes:
      - ./config/nodes/validator3:/config/keys
      - ./logs/quorum:/var/log/quorum/
      - ./config/permissions:/permissions
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.13

  validator4:
    << : *quorum-def
    ports:
      - 21004:8545/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
    volumes:
      - ./config/nodes/validator4:/config/keys
      - ./logs/quorum:/var/log/quorum/
      - ./config/permissions:/permissions
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.14

  rpcnode:
    << : *quorum-def
    container_name: rpcnode
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
      - 30303
      - 9545
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
    volumes:
      - ./config/nodes/rpcnode:/config/keys
      - ./logs/quorum:/var/log/quorum/
      - ./config/permissions:/permissions
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.15




  explorer:
    image: consensys/quorum-explorer:${QUORUM_EXPLORER_VERSION:-latest}
    volumes:
      - ./quorum-explorer/config.json:/app/config.json
      - ./quorum-explorer/env:/app/.env.production
    depends_on:
      - rpcnode
    ports:
      - 25000:25000/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.31


networks:
  quorum-dev-quickstart:
    name: quorum-dev-quickstart
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24


  # prometheus:
  #   image: "prom/prometheus"
  #   volumes:
  #     - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheus:/prometheus
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.yml
  #   ports:
  #     - 9090:9090/tcp
  #   networks:
  #     quorum-dev-quickstart:
  #       ipv4_address: 172.16.239.32

  # grafana:
  #   image: "grafana/grafana"
  #   environment:
  #     - GF_AUTH_ANONYMOUS_ENABLED=true
  #     - GF_USERS_VIEWERS_CAN_EDIT=true
  #   volumes:
  #     - ./config/grafana/provisioning/:/etc/grafana/provisioning/
  #     - grafana:/var/lib/grafana
  #   ports:
  #     - 3000:3000/tcp
  #   networks:
  #     quorum-dev-quickstart:
  #       ipv4_address: 172.16.239.33

  # loki:
  #   image: "grafana/loki"
  #   volumes:
  #     - ./loki/loki.yml:/etc/loki/local-config.yaml:ro
  #   command: -config.file=/etc/loki/local-config.yaml
  #   ports:
  #     - 3100:3100/tcp
  #   networks:
  #     quorum-dev-quickstart:
  #       ipv4_address: 172.16.239.34
  
  # promtail:
  #   image: "grafana/promtail"
  #   volumes:
  #     - ./logs:/var/log
  #     - ./promtail/promtail.yml:/etc/promtail/config.yml:ro
  #   command: -config.file=/etc/promtail/config.yml
  #   networks:
  #     quorum-dev-quickstart:
  #       ipv4_address: 172.16.239.35





# volumes:
#   splunk:
#   ethlogger:
#   prometheus:
#   grafana:
#   blockscoutpostgres:
